server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  location /config.json {
    add_header Cache-Control "no-store";
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
}
